name: Trigger Pull to Private Fork
permissions:
  contents: read
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  trigger-pull:
    if: github.event.pull_request.merged && (github.repository == 'kandji-inc/iructl') && !contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: arc-scale-set-sddx-small
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ secrets.INTERNAL_REPO_TOKEN }}
          repository: ${{ secrets.INTERNAL_REPO }}
          event-type: pr-merged-public-main
          client-payload: '{"event": ${{ toJson(github.event) }}}'
